### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davidkingzyb** [davidkingzyb/SCAST#2]
- ~use SCAST.js compiler support multiple language~
- [x] Parse by typescript compiler support typescript
- [x] Supports multiple programming paradigms including functional, procedural, and more.
- [x] Same name method in different class pointer error fix.
- [x] Support js
- [ ] Support vue component
- [x] Support csharp

**Comment by davidkingzyb** [comment]
- [x] support python
- [ ] typescript use ESTree parse
- [ ] python use ESTree parse
- [x] MCP server
- [x] Ollama Ai
